---
- name: Install required packages on RHEL 9.6
  hosts: kvms
  become: true
  tasks:
    - name: Register system with Red Hat Subscription Manager
      name: Register as rhuser with rhpassword  and auto-subscribe to available content.
      community.general.redhat_subscription:
        state: present
        username: r**********
        password: r**********
        auto_attach: true

    - name: Install required packages
      ansible.builtin.dnf:
        name:
          - subscription-manager
          - python3
          - python3-pip
          - gcc
          - libffi-devel
          - python3-devel
          - openssl-devel
          - wget 
          - curl 
          - tree
          - tmux
          - git
        state: present

