---
- name: Install and configure Pacemaker HA Cluster on RHEL 9.6 KVM1 node
  hosts: kvms
  become: true
  vars:
    cluster_name: "kvm-ha-cluster"
    cluster_nodes:
      - vcollab-kvm1.cloud.vssi.com
      - vcollab-kvm2.cloud.vssi.com

  tasks:
    - name: Enable Resilient Storage repository
      ansible.builtin.command: >
        subscription-manager repos --enable=rhel-9-for-x86_64-resilientstorage-rpms
      args:
      warn: false

    - name: Enable High Availability repository
      ansible.builtin.command: >
        subscription-manager repos --enable=rhel-9-for-x86_64-highavailability-rpms
      args:
      warn: false

    - name: Install High Availability group packages
      ansible.builtin.yum:
        name: "@High Availability"
        state: present

    - name: Install Resilient Storage group packages
      ansible.builtin.yum:
        name: "@Resilient Storage"
        state: present
    - name: Install HA packages
      dnf:
        name:
          - iscsi-initiator-utils
          - device-mapper-multipath*
          - pacemaker
          - pcs
          - fence-agents-all
        state: present

    - name: Enable and start pcsd service
      systemd:
        name: pcsd
        enabled: yes
        state: started

    - name: Set hacluster user password
      user:
        name: hacluster
        password: "{{ 'Admin@123' | password_hash('sha512') }}"

    - name: Authenticate pcs cluster nodes
      shell: |
        echo Admin@123 | pcs host auth {{ cluster_nodes | join(' ') }} -u hacluster --password
      args:
        executable: /bin/bash

    - name: Setup cluster
      shell: pcs cluster setup --name {{ cluster_name }} {{ cluster_nodes | join(' ') }}
      args:
        creates: /etc/corosync/corosync.conf

    - name: Start and enable cluster
      shell: pcs cluster start --all && pcs cluster enable --all

    - name: Check cluster status
      shell: pcs status
      register: pcs_status

    - name: Show cluster status
      debug:
        var: pcs_status.stdout
        - name: Enable two_node mode for HA cluster
          shell: pcs property set stonith-enabled=false && pcs property set no-quorum-policy=ignore && pcs property set two-node=1